config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: false
  longkey: false
dotfiles:
  d_i3:
    dst: ~/.i3
    link: true
    src: i3
  d_jupyter:
    dst: ~/.jupyter
    link: true
    src: jupyter
  d_nvim:
    dst: ~/.config/nvim
    link: true
    src: config/nvim
  d_rofi:
    dst: ~/.config/rofi
    link: true
    src: config/rofi
  d_scripts:
    dst: ~/scripts
    link: true
    src: scripts
  d_user:
    dst: ~/.config/sublime-text-3/Packages/User
    link: true
    src: config/sublime-text-3/Packages/User
  f_aliases:
    dst: ~/.aliases
    link: true
    src: aliases
  f_bashrc:
    dst: ~/.bashrc
    link: true
    src: bashrc
  f_config:
    dst: ~/.vdirsyncer/config
    link: true
    src: vdirsyncer/config
  f_config.fish:
    dst: ~/.config/fish/config.fish
    link: true
    src: config/fish/config.fish
  f_fish_greeting:
    dst: ~/.config/fish/functions/fish_greeting
    link: true
    src: config/fish/functions/fish_greeting
  f_gitconfig:
    dst: ~/.gitconfig
    link: true
    src: gitconfig
  f_i3status.conf:
    dst: ~/.i3status.conf
    link: true
    src: i3status.conf
  f_kitty.conf:
    dst: ~/.config/kitty/kitty.conf
    link: true
    src: config/kitty/kitty.conf
  f_omf.fish:
    dst: ~/.config/fish/conf.d/omf.fish
    link: true
    src: config/fish/conf.d/omf.fish
  f_profile:
    dst: ~/.profile
    link: true
    src: profile
profiles:
  pspri:
    dotfiles:
    - f_aliases
    - d_i3
    - f_bashrc
    - f_profile
    - d_scripts
    - d_nvim
    - f_kitty.conf
    - d_user
    - f_gitconfig
    - f_i3status.conf
    - f_config
    - d_jupyter
    - f_config.fish
    - f_fish_greeting
    - f_omf.fish
    - d_rofi
